### ISSUE TITLE
cocos项目如何用chrome真机调试？

### ISSUE THREAD

**Issue by y573754216** [vivominigame/issues#100]
文档关于:cocos2.0.10项目版本的chrome真机测试

- [ ] 缺失
- [ ] 错误
- [x] 不确定？

### 详细描述
根据文档的需求打成调试包，电脑手机已处于同一局域网，npm开启（因为是2.0.10版本手动npm生成二维码），手机通过二维码进游戏，电脑根据手机的ip地址连接不上,调试终止。。

**Comment by jesseband** [comment]
这个在首页的readme里面就有快捷入口
https://github.com/vivominigame/issues/issues/9
