### ISSUE TITLE
request可以用get请求，用post得不到相应会报错

### ISSUE THREAD

**Issue by linqw075** [vivominigame/issues#101]
request可以用get请求，用post得不到相应会报错

**Comment by jesseband** [comment]
那就使用request呀，报错是报什么错误，怎么写的代码，提供个demo包，请求的是后端服务，和后端确认下

**Comment by linqw075** [comment]
代码：
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cf.request({
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;url:&nbsp;'https://jlmhd.zhhainiao.com/gameHandler.ashx',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data:&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;act:&nbsp;"getGameStatus",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;version:&nbsp;'1.0.3'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;method:&nbsp;'POST',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dataType:&nbsp;'json',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;success:&nbsp;function&nbsp;(res)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;console.log("----------success&nbsp;res=",&nbsp;res);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fail:&nbsp;function&nbsp;(res)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;console.log("----------fail&nbsp;res=",&nbsp;res);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})




报错：



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jesse-band"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月24日(星期二) 下午2:41
收件人:&nbsp;"vivominigame/issues"<issues@noreply.github.com&gt;;
抄送:&nbsp;"风影零星"<252631790@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vivominigame/issues] request可以用get请求，用post得不到相应会报错 (#101)




那就使用request呀，报错是报什么错误，怎么写的代码，提供个demo包，请求的是后端服务，和后端确认下

**Comment by linqw075** [comment]
代码：
qg.request({
            url: 'https://jlmhd.zhhainiao.com/gameHandler.ashx',
            data: {
                act: "getGameStatus",
                version: '1.0.3'
            },
            method: 'POST',
            dataType: 'json',
            success: function (res) {
                console.log("----------success res=", res);
            },
            fail: function (res) {
                console.log("----------fail res=", res);
            }
        })

**Comment by linqw075** [comment]
报错：
SyntaxError: Unexpected end of JSON input
    at XMLHttpRequest.o.onreadystatechange ((no filename):1:38317)

**Comment by jesseband** [comment]
> 报错：
> SyntaxError: Unexpected end of JSON input
> at XMLHttpRequest.o.onreadystatechange ((no filename):1:38317)

找后端确认下 post返回数据不对，使用postman调试好接口再去调用

**Comment by linqw075** [comment]
但在微信端是没问题的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jesse-band"<notifications@github.com&gt;; 
发送时间: 2019年12月24日(星期二) 下午3:28
收件人: "vivominigame/issues"<issues@noreply.github.com&gt;; 
抄送: "风影零星"<252631790@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vivominigame/issues] request可以用get请求，用post得不到相应会报错 (#101)



 
报错：
 SyntaxError: Unexpected end of JSON input
 at XMLHttpRequest.o.onreadystatechange ((no filename):1:38317)
  
找后端确认下 post返回数据不对，使用postman调试好接口再去调用

**Comment by jesseband** [comment]
get能获取到，那就使用get
