### ISSUE TITLE
vivo调login接口获取账号授权点击同意按钮没有得到响应

### ISSUE THREAD

**Issue by linqw075** [vivominigame/issues#103]
vivo调login接口获取账号授权点击同意按钮没有得到响应，点击取消按钮可以得到响应

**Comment by jesseband** [comment]
没有报错信息的吗？
提供下写法和demo

**Comment by linqw075** [comment]
qg.login().then((res) => {
      if (res.data.token) {
        // 使用token进行服务端对接
      }
  }, (err) => {
      console.log('登录失败' + JSON.stringify(err));
  });

就直接调用这个

**Comment by jesseband** [comment]
res.token 使用这个获取

**Comment by linqw075** [comment]
qg.login().then((res) => {
                    console.log('登录成功 ');
                }, (err) => {
                    console.log('登录失败 ' + JSON.stringify(err));
                });

调用以上登录接口代码，点击‘同意’按钮，登录成功还是得不到响应，但取消可以得到，这是什么问题？
以下是点取消按钮输出的日志:
登录失败 {"data":{"errMsg":"authorize failed","errCode":403},"code":403}

**Comment by jesseband** [comment]
确认下是否使用的是vivo手机
