### ISSUE TITLE
laya2.2打包3d游戏黑屏,无log

### ISSUE THREAD

**Issue by 512524243** [vivominigame/issues#104]
### 相关信息
- 问题类型
不清楚

- 引擎版本
不清楚

- 手机型号
不清楚

- 操作系统
windows 10

- IDE版本
laya2.2

- toolkit版本
toolkit 0.3.2

### 问题描述
laya2.2打包的游戏黑屏,无log

### 复现步骤
见复现demo
[http://47.92.7.194/test.zip](url)

### 联系方式
dhfdxh

**Comment by jesseband** [comment]
参考 https://ask.layabox.com/question/44015

**Comment by 512524243** [comment]
> 参考 https://ask.layabox.com/question/44015

不行,试过这个方法了,还是无法解决这个问题

**Comment by jesseband** [comment]
toolkit 0

> > 参考 https://ask.layabox.com/question/44015
> 
> 不行,试过这个方法了,还是无法解决这个问题

toolkit 0.3.2  版本太老了，laya升级到最新版本

首页就写的遇到问题先升级到最新版本试试
