### ISSUE TITLE
调用 登录token获取用户信息 老是返回 {   "msg": "参数不合法",   "code": 20000 }

### ISSUE THREAD

**Issue by tiredfan** [vivominigame/issues#110]
https://minigame.vivo.com.cn/documents/#/api/service/newaccount
根据文档调用，接口 https://quickgame.vivo.com.cn/api/quickgame/cp/account/userInfo 老是返回
{
  "msg": "参数不合法",
  "code": 20000
}
这个你们示例的代码 也是如此：
https://quickgame.vivo.com.cn/api/quickgame/cp/account/userInfo?pkgName=com.hybrid.demo.sample&token=5d2bebd1f347b5cee4a28226650f4171fae6bb0859312f62a306168ccd67a3c3&timestamp=1567130880000&nonce=4687864651684984&signature=87ed863c1b31ae81a02939c1b469fd8828489ccd47d3a487773a24e921191453

**Comment by jesseband** [comment]
参考 https://github.com/vivominigame/issues/issues/35

**Comment by jesseband** [comment]
多数情况是支付和账户的弄混了
![image](https://user-images.githubusercontent.com/12119512/68189319-07cdce80-ffe6-11e9-936a-3f8b2addbff8.png)
账户使用账户的
支付服务才使用支付的
