### ISSUE TITLE
2D绘制黑屏

### ISSUE THREAD

**Issue by idler8** [vivominigame/issues#113]
### 相关信息
- 问题类型
引擎

- 引擎版本
vivo 1057

- 手机型号
vivo Z3

- 操作系统
Mac

- IDE版本
VSCode

- toolkit版本
最新

### 问题描述
使用最小案例绘制2D文本显示黑屏
### 调试结果
![image](https://user-images.githubusercontent.com/50684820/71576482-cfe99000-2b2b-11ea-9eec-4af991f431f2.png)

### 复现步骤
使用如下代码打包测试
```javascript
console.log(1);
var Canvas = qg.createCanvas();
console.log(Canvas);
var Context = Canvas.getContext('2d');
console.log(Context);
Context.fillStyle = '#FFFFFF';
console.log(Context.fillStyle);
Context.font = '40px Arial';
console.log(Context.font);
Context.textAlign = 'center';
console.log(Context.textAlign);
Context.textBaseline = 'middle';
console.log(Context.textBaseline);
Context.fillText('Hello world', 100, 100);
console.log('绘制完毕');
```

### 联系方式
QQ:875381750

**Comment by jesseband** [comment]
使用的哪个第三方引擎导出的？

**Comment by HooRang** [comment]
同样问题，代码已成功执行完。但一直黑屏

**Comment by jesseband** [comment]
> 同样问题，代码已成功执行完。但一直黑屏

canvas上屏暂时不支持
