### ISSUE TITLE
qg.login之后在后端使用api获取openid等信息是，总是返回retcode:20000的错误

### ISSUE THREAD

**Issue by a1027794510a** [vivominigame/issues#114]
### 相关信息
- 问题类型

接口问题
- 引擎版本

- 手机型号

- 操作系统

- IDE版本

- toolkit版本

### 问题描述

1，前端使用qg.login()登陆，能成功拿到token

2，后端使用此token，通过https://minigame.vivo.com.cn/documents/#/api/service/newaccount?
id=login 这里文档的API：https://quickgame.vivo.com.cn/api/quickgame/cp/account/userInfo 请求用户openid和其他信息，此时的返回总是{retcode: 20000}
2.1、确认Content-Type:application/json
2.2、确认 GET请求
2.3、用postman试过也不行

3，我们已经反复检查，确认区分了帐号参数和支付参数 

4，retcode = 20000具体是什么含义呢，可以在哪里查看错误码的说明？

5、为什么官网api文档里面的示例也是返回 参数不合法？

**Comment by jesseband** [comment]
20000 是验签不通过，或必要参数为空
需要我们这边技术去群里对接，找下商务拉下对应技术

**Comment by a1027794510a** [comment]
@jesseband  我确认了，依旧是同样的结果，麻烦请看看，这些参数哪个不对？
![微信截图_20191231111455](https://user-images.githubusercontent.com/20679063/71608880-484d6100-2bbf-11ea-812d-c4243bb9eb6d.png)
![TIM图片20191231111550](https://user-images.githubusercontent.com/20679063/71608887-5307f600-2bbf-11ea-87e9-46fb31a097ef.png)

**Comment by jesseband** [comment]
什么时候在开平创建的

**Comment by a1027794510a** [comment]
@jesseband 2019-09-05

**Comment by jesseband** [comment]
> @jesseband 2019-09-05

已经修复了，这边数据同步有点问题

**Comment by a1027794510a** [comment]
@jesseband 
你好，这边还是一样情况
签名参数
![image](https://user-images.githubusercontent.com/20679063/71777338-6f4dcd80-2fd9-11ea-82d1-fb7906730c29.png)

发送参数
![image](https://user-images.githubusercontent.com/20679063/71777357-ba67e080-2fd9-11ea-9b41-b4458c82e379.png)

结果
![image](https://user-images.githubusercontent.com/20679063/71777359-c2278500-2fd9-11ea-95d3-4cf503161c57.png)

**Comment by jesseband** [comment]
> @jesseband
> 你好，这边还是一样情况
> 签名参数
> ![image](https://user-images.githubusercontent.com/20679063/71777338-6f4dcd80-2fd9-11ea-82d1-fb7906730c29.png)
> 
> 发送参数
> ![image](https://user-images.githubusercontent.com/20679063/71777357-ba67e080-2fd9-11ea-9b41-b4458c82e379.png)
> 
> 结果
> ![image](https://user-images.githubusercontent.com/20679063/71777359-c2278500-2fd9-11ea-95d3-4cf503161c57.png)

联系方式是什么，在对接群反馈下
