### ISSUE TITLE
Cocos 小包模式 从服务器下载不了文件，其他小游戏可以设置域名服务器，vivo我要在哪填写服务器域名？

### ISSUE THREAD

**Issue by Jonle** [vivominigame/issues#124]
Cocos 小包模式 打开游戏后用android studio 查log 显示 文件不能下载，但是浏览器可以访问。
### 相关信息
- 问题类型
 不清楚

- 引擎版本
vivo 1050

- 手机型号
mi 8

- 操作系统
win7

wechat
Jonle776440448

**Comment by techbirds** [comment]
我们这边暂没有提供填写资源服务器域名的入口。
