### ISSUE TITLE
水滴屏幕判断高度

### ISSUE THREAD

**Issue by MuLodMan** [vivominigame/issues#125]
https://minigame.vivo.com.cn/documents/#/api/system/system-info?id=qggetnotchheightsync 
请问 这个方法能判断水滴屏幕吗？我的手机调用返回的height是0,机型为 oppo k1。 还是说我必须用vivo的手机才能获得正确的信息呢？

**Comment by jesseband** [comment]
引擎版本是多少，使用vivo手机测试
