### ISSUE TITLE
载入banner 没有回调，banner无法显示 

### ISSUE THREAD

**Issue by MuLodMan** [vivominigame/issues#127]
载入banner 没有回调，banner无法显示 ，onload 和onError 均无反馈。机型：vivo x21A。1月6号onError还会触发，1月7号后不会触发。其他vivo手机可以。

**Comment by jesseband** [comment]
参考 https://github.com/vivominigame/issues/issues/73

**Comment by MuLodMan** [comment]
@jesseband :我怀疑vivo的广告测试是不是有封机器的策略，刚才出现了同样的情况（使用的是正常测试机，以前该测试机从来没出现这种情况）。
