### ISSUE TITLE
能否在用户不授权的情况下获取用户openId

### ISSUE THREAD

**Issue by Castaway74** [vivominigame/issues#130]
### 需求描述

获取用户的openId
### 需求场景

在游戏加载前需要获取用户openid，根据openId获取用户信息决定下一步加载内容，但是不希望拉起授权框打断用户体验
### 参考

参考微信登录接口，提供登录凭证，通过凭证进而换取用户登录态信息，包括用户的唯一标识（openid），此部分不需要用户授权

**Comment by jesseband** [comment]
下个版本我们会升级授权流程，不需要用户点击
这个授权框对于小游戏而言只会弹一次，所以其他游戏如果有授权过，就不需要弹起了
