### ISSUE TITLE
平台自动弹框

### ISSUE THREAD

**Issue by MuLodMan** [vivominigame/issues#131]
![image](https://user-images.githubusercontent.com/24437520/72131813-528a0f00-33b8-11ea-8ffb-05b8e81d541f.png)

请问一下，是不是只要js脚本出错或者抛出异常就会出现这个提示啊，审核被打回，提示进入不了游戏。但在我的测试机上，从来没弹出过这个对话框，游戏也可以正常运行。（机型:vivox21A,快应用调试器平台版本号:1057）

**Comment by jesseband** [comment]
我们1054版本就已经修改，去掉了这个弹窗，请确认下版号

**Comment by MuLodMan** [comment]
@jesseband  好的
