### ISSUE TITLE
laya发布vivo小游戏问题

### ISSUE THREAD

**Issue by J-Diana** [vivominigame/issues#139]
laya1.0版本，发布vivo小游戏的日志报错：找不到index.js文件，但是界面显示发布成功，不生成build和dist文件夹，生成的game.js里引用了index.js文件。修改game.js，采用cmd执行npm run build，构建的rpk包游戏黑屏，日志显示只执行到APP Framework 初始化框架 App，游戏就进行不了了，使用layaIDE最新版依然如此。

**Comment by jesseband** [comment]
laya版本升级下 升级到1.8.5
打包导出vivo小游戏时，需要先编译游戏的
