### ISSUE TITLE
调用login接口拉起授权后用户取消授权该怎么处理

### ISSUE THREAD

**Issue by w244623321** [vivominigame/issues#140]
调用login接口拉起授权后用户取消授权该怎么处理，是强制退出游戏，还是重新拉起授权

**Comment by jesseband** [comment]
![image](https://user-images.githubusercontent.com/12119512/74897865-4770c880-53d3-11ea-92f1-60441af8adc9.png)
https://minigame.vivo.com.cn/documents/#/api/service/newaccount?id=login
这个有规范，这边看一下

**Comment by jesseband** [comment]
上面那个是规范
如果问题是错误的话，要把截图以及操作复现路径等等都描述清楚还有vivo快应用的版本
