### ISSUE TITLE
cc.audioEngine.playMusic() 失效

### ISSUE THREAD

**Issue by Peach0810** [vivominigame/issues#142]
![image](https://user-images.githubusercontent.com/61271724/75230435-90b78280-57ee-11ea-9d96-ad8fe4206798.png)

cc.audioEngine.playMusic()  这个在vivo小游戏上面 没效果 请问下  你们是不支持了吗  cocos 版本2.0.10

**Comment by jesseband** [comment]
cocos 2.0.10 版本升级到2.2.0版本以及以上版本，如果有兼容问题，登录下cocos论坛查询是否有同类问题解答，如还不能解决，询问下cocos的技术支持
