### ISSUE TITLE
分包加载报错 Cannot read property 'loadSubpackageProgress'

### ISSUE THREAD

**Issue by hlxabcd** [vivominigame/issues#146]
分包加载监听ON_ERROR 报错
{"message":"(see stack)
Uncaught TypeError: Cannot read property 'loadSubpackageProgress' of undefined
[0]_._OnLoadSubpackageProgressUpate@(no filename):1"}

请问这个是什么原因？是使用问题吗？

**Comment by jesseband** [comment]
使用方法 参考 https://minigame.vivo.com.cn/documents/#/lesson/base/subpackage
按照这里面的demo写

**Comment by hlxabcd** [comment]
现象是，有的分包可以下载成功。有的汇报这个错。并且不是必现。

**Comment by jesseband** [comment]
是首次加载失败？升级引擎到1058，这个是已知问题，新版本已经解决
