### ISSUE TITLE
账户API对接问题--MD5签名顺序字母序是什么意思？

### ISSUE THREAD

**Issue by Ranphy** [vivominigame/issues#15]
1、在文档中4.1.2 应用服务器根据code获取access_token中提到签名需要使用md5签名，签名顺序字母序
麻烦解释一下签名顺序字母序是指什么意思？谢谢
2、scope参数，如果小游戏打开时需要用户手动点击确认授权时应该需要传递什么参数？

**Comment by jesseband** [comment]
签名顺序字母序  就是abcd到xyz的顺序

**Comment by Ranphy** [comment]
是值将client_id,code,grant_type,nonce,redirect_url,timestamp放在map中使用PartnerSignUtil工具类进行签名是嘛？

**Comment by Ranphy** [comment]
还是指将abcd~xyz进行签名？

**Comment by Ranphy** [comment]
scope参数，如果小游戏打开时需要用户手动点击确认授权时应该需要传递什么参数？

**Comment by jesseband** [comment]
具体看下文档，所有的操作都在文档里面

**Comment by Ranphy** [comment]
是指将client_id,code,grant_type,nonce,redirect_url,timestamp放在map中使用PartnerSignUtil工具类进行签名是嘛？

**Comment by jesseband** [comment]
> scope参数，如果小游戏打开时需要用户手动点击确认授权时应该需要传递什么参数？

是否授权确认授权 跟scope参数无关
scope是用来区分获取用户哪些信息的
目前帐户只支持一种 按照文档上的写就行了

**Comment by Ranphy** [comment]
请求https://passport.vivo.com.cn/oauth/2.0/access_token这个接口得时候，需要生成sign，这个sign是指将client_id,code,grant_type,nonce,redirect_url,timestamp放在map中使用PartnerSignUtil工具类生成是嘛？

**Comment by Ranphy** [comment]
请求https://passport.vivo.com.cn/oauth/2.0/access_token 这个接口得时候，需要传递sign参数，这个sign是指将client_id,code,grant_type,nonce,redirect_url,timestamp放在map中使用PartnerSignUtil工具类生成是嘛？

**Comment by Ranphy** [comment]
回调得地址，使用redirect_url 还是redirect_uri进行urlencode 然后传递参数

**Comment by jesseband** [comment]
> 请求https://passport.vivo.com.cn/oauth/2.0/access_token 这个接口得时候，需要传递sign参数，这个sign是指将client_id,code,grant_type,nonce,redirect_url,timestamp放在map中使用PartnerSignUtil工具类生成是嘛？

具体看下文档，所有的操作都在文档里面
还有个问题整理可以参考
https://minigame.vivo.com.cn/documents/#/lesson/question/question-account

**Comment by jesseband** [comment]
> > 请求https://passport.vivo.com.cn/oauth/2.0/access_token 这个接口得时候，需要传递sign参数，这个sign是指将client_id,code,grant_type,nonce,redirect_url,timestamp放在map中使用PartnerSignUtil工具类生成是嘛？
> 
> 具体看下文档，所有的操作都在文档里面
文档地址 https://minigame.vivo.com.cn/documents/api/service/assets/account.docx
> 还有个问题整理可以参考
> https://minigame.vivo.com.cn/documents/#/lesson/question/question-account
