### ISSUE TITLE
原生广告的接入如何来进行跳转动作？

### ISSUE THREAD

**Issue by an2us** [vivominigame/issues#153]
原生广告的接入，通过返回广告数据 adList，其实拿到显示广告的图片地址之类的进行显示，，如果玩家产生了点击，那这个点击的交互动作，如何来做呢？ 访问某个网址？或下载某个应用，但从adList的值中也看不出来要交互动作的相关值（比如要跳转到的网址地址也没有啊？）
玩家点击跳转的动作是由我们自己来做还是如何处理呢？

**Comment by an2us** [comment]
![image](https://user-images.githubusercontent.com/61858413/76050781-a6be0380-5fa3-11ea-89e5-58ecb8151f62.png)
返回的adlist中的数据定义了交互的类型，但并没有定义需要跳转到的APk或小游戏的网址之类的。。

**Comment by weixing02** [comment]
原生广告是通过上报曝光和上报点击来实现交互的，跳转逻辑不需要游戏侧来控制，只需要调用reportAdShow和reportAdClick，如果正确上报曝光和上报点击后，会自动进行跳转的，参考原生广告开发文档。
https://minigame.vivo.com.cn/documents/#/api/da/native-ad
![image](https://user-images.githubusercontent.com/7108005/76073437-8e1a1180-5fd4-11ea-8007-5a4f338ab3e9.png)
