### ISSUE TITLE
cocos2.3.1 设置分包后 用设备调试出现黑屏

### ISSUE THREAD

**Issue by T--T** [vivominigame/issues#156]
### 相关信息
- 问题类型
引擎

- 引擎版本
vivo 1058
快应用 1.5.8.7-RC-00

- 手机型号
vivo x9i

- 操作系统
Macos 10.15.3

#### 游戏启动后黑屏 
chrome输出
![72253197-8769-4A36-A8B9-903C57567C80](https://user-images.githubusercontent.com/3961009/76411113-141acb80-63cc-11ea-91e8-60f563eff5a0.png)

#### 新建一个项目 新建一个目录设置为分包 例如新建了一个ts的示例项目 baseRes设置为分包
![36C72DA1-D050-4E85-9BFF-DF8E9834AF5C](https://user-images.githubusercontent.com/3961009/76410892-a7073600-63cb-11ea-8058-e062c56ffee3.png)

#### cocos构建参数如下
![C4FF654C-04F5-4E95-A0DF-59166D3D00A5](https://user-images.githubusercontent.com/3961009/76410936-bc7c6000-63cb-11ea-884f-a8a592821985.png)

### 联系方式
邮箱 yush329@qq.com

**Comment by jesseband** [comment]
下载分包调试器
https://minigame.vivo.com.cn/documents/#/download/debugger
报错日志分析
