### ISSUE TITLE
分包后整包14M   云真机不能运行

### ISSUE THREAD

**Issue by AuLeeHey** [vivominigame/issues#158]
Q1:我分包后  整包有14M  大   在云真机上不能运行  
Q2:分包后  上传包直接上传这个14M的整包 就可以吗

**Comment by AuLeeHey** [comment]
Q1补充  云真机上传rpk  进度条到100%后就卡在那里    没有出现上传成功的提示
![UOE@ 3KO82GQLUO@0P)W_IJ](https://user-images.githubusercontent.com/59221048/77023048-2dbca400-69c6-11ea-9edb-69f97509ff12.png)

**Comment by jesseband** [comment]
换个云真机
最好本地有手机测试
找下云测平台的客服

**Comment by AuLeeHey** [comment]
> 换个云真机
> 最好本地有手机测试
> 找下云测平台的客服

主要是第二个问题   分包上传的话   直接传14M的整包 就可以吗?

**Comment by jesseband** [comment]
> > 换个云真机
> > 最好本地有手机测试
> > 找下云测平台的客服
> 
> 主要是第二个问题 分包上传的话 直接传14M的整包 就可以吗?

理论上应该是可以的，你上个小体积的包可以？大的就不行了吗？

**Comment by AuLeeHey** [comment]
> > > 换个云真机
> > > 最好本地有手机测试
> > > 找下云测平台的客服
> > 
> > 
> > 主要是第二个问题 分包上传的话 直接传14M的整包 就可以吗?
> 
> 理论上应该是可以的，你上个小体积的包可以？大的就不行了吗？

感谢回答   问题已解决  
Q1:云测用的是整包解压后  取出原包在云测
Q2:小于16M的整包都可以上传   但是要求整包内的  主包和分包都小于4M  (可通过解压工具查看)
