### ISSUE TITLE
对不起,游戏好像出了点问题

### ISSUE THREAD

**Issue by zj666666** [vivominigame/issues#177]
对不起,游戏好像出了点问题.
请问这是怎么回事啊?
![1587146129(1)](https://user-images.githubusercontent.com/12823664/79599226-b8083d00-8117-11ea-9516-7ca9c607b899.jpg)

**Comment by jesseband** [comment]
循环报错导致的，查看日志看下
https://minigame.vivo.com.cn/documents/#/lesson/dev/dev-chrome
https://minigame.vivo.com.cn/documents/#/lesson/dev/dev-log
