### ISSUE TITLE
请问下原生h5能否实现接入vivo小游戏

### ISSUE THREAD

**Issue by IMDreamCatcher** [vivominigame/issues#178]
我这边有一个用ImpactJS开发的原生h5游戏需要接入vivo小游戏
我看官方文档说的接入方式都是基于一些游戏引擎开发的游戏，所以想问下原生的h5有没有接入的可能，是使用js+canvas实现的
并且我这边在game.js里写了一个简单使用canvas添加背景图片的功能 打开之后总是黑屏，也不知道哪里错了qgame-adapter.js是已经引用的了 下面是代码：

require('qgame-adapter');

if (window.mainCanvas) {
    window['canvas'] = window.mainCanvas;
}

var ctx = canvas.getContext('2d');
var image = qg.createImage();
image.src='./img/bg.jpg';

image.onload=function(){
	console.debug("加载完毕");
	ctx.drawImage(image,0,0);
}

或者你们有类似原生h5转rpk的demo吗？
我这边没有接触过js 所以问题可能有点蠢 见谅

**Comment by shixforever** [comment]
目前不支持直接绘制，后续会提供绘制demo

**Comment by IMDreamCatcher** [comment]
> 目前不支持直接绘制，后续会提供绘制demo

也就是说目前不支持转换成vivo小游戏咯？游戏是html+js+css做的

**Comment by jesseband** [comment]
html不支持的，这个代码还缺webgl 渲染的逻辑
