### ISSUE TITLE
使用wx2mg的时候，打包跑进了死循环

### ISSUE THREAD

**Issue by SmileRainAlone** [vivominigame/issues#180]
### 相关信息
- 问题类型
不清楚

- 引擎版本
cocos creator1.9.3打包微信小游戏

- 手机型号
无

- 操作系统
window10

- IDE版本
无

- toolkit版本
无

### 问题描述
如题，我们原本的项目是用cocos1.9.3开发，不能直接发布vivo游戏，遂选择官方提供的微信小游戏转vivo游戏打包工具 wx2mg。在时候用的时候发现，打包工具一直循环打包，每一次都会在新建的vivo项目目录下的scr文件夹中创建新的vivo项目，并一直打包下去。

### 复现步骤
 1. 使用cocos creator 1.9.3打包成微信小游戏
 2. 使用官方文档的wx2mg转工程
 3. 之后会一直打包，暂停打包会发现打包进程在循环打包，不停的在src目录下创建新的工程

### 联系方式

wx: DenonSlience

**Comment by jesseband** [comment]
建议cocos版本升级，直接使用cocos版本去导出vivo小游戏
