### ISSUE TITLE
H5的audio属性

### ISSUE THREAD

**Issue by chenyu0532** [vivominigame/issues#181]
let myAudio = document.createElement('audio');
                myAudio.setAttribute('src', cc.url.raw('resources/sound/' + this.sufi +  '/' + this.sufi + _.tag1 + '.mp3'));
myAudio.playbackRate = 0.7;
myAudio.play();

请问下，小游戏平台支不支持创建audio。。以及支不支持playbackRate属性

**Comment by jesseband** [comment]
https://minigame.vivo.com.cn/documents/#/api/media/audio
