### ISSUE TITLE
RPK上传失败

### ISSUE THREAD

**Issue by Gainhero** [vivominigame/issues#190]
上传小游戏包RPK包，显示应用包解析失败，失败原因：RPK文件没有配置type属性 

### 相关信息
- 问题类型

- 引擎版本

- 手机型号

- 操作系统

- IDE版本

- toolkit版本

**Comment by jesseband** [comment]
检查下配为什么没有打出来 https://minigame.vivo.com.cn/documents/#/lesson/game/configuration
三方引擎升级到最新版本尝试下
