### ISSUE TITLE
分包导致包体过大

### ISSUE THREAD

**Issue by wuzhidong1** [vivominigame/issues#20]
图1为项目目录，其中shoal为分包
![9WV4%FT$(BW($H0TXAXS(O](https://user-images.githubusercontent.com/57163071/67824581-c2029900-fb01-11e9-9502-a21b22b9e673.png)

![F`@AZZL}OLS~(SE4 MXAGBR](https://user-images.githubusercontent.com/57163071/67824660-ff672680-fb01-11e9-90c0-6e5987a34463.png)

![Z0AAOTXURF1BWWO8FTBSCC](https://user-images.githubusercontent.com/57163071/67824669-02faad80-fb02-11e9-8d63-c2dfc95ba410.png)

![23M~HK4$B82S%~U3OZ61)PX](https://user-images.githubusercontent.com/57163071/67824673-055d0780-fb02-11e9-9cd8-f2cdea9c3d0c.png)

![51Y(NWM$I`R5DFXUOTG3O08](https://user-images.githubusercontent.com/57163071/67824678-068e3480-fb02-11e9-9b25-338062ac42e5.png)

此项目编译后生成一个rpk文件，其中把rpk文件解压后得到图2的3个rpk，分别把3个rpk解压，得到图3~5的文件，其中图3和图4~5的资源都有重复的部分，而分包最大不能超出12M，如此多的重复文件导致包体很容易超12M

**Comment by jesseband** [comment]
这个是有原整包在里面的，需要兼容之前的
https://minigame.vivo.com.cn/documents/#/lesson/base/subpackage

release包把map文件去掉

**Comment by wuzhidong1** [comment]
> 这个是有原整包在里面的，需要兼容之前的
> https://minigame.vivo.com.cn/documents/#/lesson/base/subpackage
> 
> release包把map文件去掉



> 这个是有原整包在里面的，需要兼容之前的
> https://minigame.vivo.com.cn/documents/#/lesson/base/subpackage
> 
> release包把map文件去掉

**Comment by wuzhidong1** [comment]
> 这个是有原整包在里面的，需要兼容之前的
> https://minigame.vivo.com.cn/documents/#/lesson/base/subpackage
> 
> release包把map文件去掉

“目前打出来的包体体积会比之前的大是正常的，为了兼容把原先的整包也打进去了“请问这个在编译的时候能否选择不兼容模式，因为分包后代码基本都在8M左右，再加上这个兼容的话已16M，编辑器无法编译通过了

**Comment by jesseband** [comment]
> > 这个是有原整包在里面的，需要兼容之前的
> > https://minigame.vivo.com.cn/documents/#/lesson/base/subpackage
> > release包把map文件去掉
> 
> “目前打出来的包体体积会比之前的大是正常的，为了兼容把原先的整包也打进去了“请问这个在编译的时候能否选择不兼容模式，因为分包后代码基本都在8M左右，再加上这个兼容的话已16M，编辑器无法编译通过了

这个上传规则后续会放开为16M，现在先压缩下，map文件去掉看看，目前规则是12M

**Comment by wuzhidong1** [comment]
> > > 这个是有原整包在里面的，需要兼容之前的
> > > https://minigame.vivo.com.cn/documents/#/lesson/base/subpackage 
> > > release包把地图文件去掉
> > 
> > 
> > “目前打出来的包体体积会比之前的大是正常的，为了兼容把原先的整包也打进去去”“请问这个在编译的时候能否选择不兼容模式，因为分包后代码基本都在8M左右，再加上这个兼容的话已16M，编辑器无法编译通过了
> 
> 这个上传规则后续会放开为16M，现在先压缩下，map文件去掉看看，目前规则是12M

只能等后续优化了吗？因现在所有分包代码已经是压缩过的了。未压缩前就分包代码都达到14M，而且debug版也用压缩后的话，代码基本就不能调试了，找问题是变得很困难

**Comment by jesseband** [comment]
> > > > 这个是有原整包在里面的，需要兼容之前的
> > > > https://minigame.vivo.com.cn/documents/#/lesson/base/subpackage
> > > > release包把地图文件去掉
> > > 
> > > 
> > > “目前打出来的包体体积会比之前的大是正常的，为了兼容把原先的整包也打进去去”“请问这个在编译的时候能否选择不兼容模式，因为分包后代码基本都在8M左右，再加上这个兼容的话已16M，编辑器无法编译通过了
> > 
> > 
> > 这个上传规则后续会放开为16M，现在先压缩下，map文件去掉看看，目前规则是12M
> 
> 只能等后续优化了吗？因现在所有分包代码已经是压缩过的了。未压缩前就分包代码都达到14M，而且debug版也用压缩后的话，代码基本就不能调试了，找问题是变得很困难

debug版本应该不设置大小的，只有release包上传到开发者平台才会现在整体大小
