### ISSUE TITLE
使用wx2mg的时候，打包跑进了死循环

### ISSUE THREAD

**Issue by oowen1985** [vivominigame/issues#201]
### 相关信息
- 问题类型：发布

- 引擎版本：基于pixi.js的源生js

- 手机型号：无

- 操作系统：windows10

- IDE版本：无

- toolkit版本：无

### 问题描述
使用官方提供的微信小游戏转vivo游戏打包工具 wx2mg时，会不断循环发布vivo-qgame/src/vivo-qgame/src/...，并一直循环执行

### 复现步骤
使用官方文档的wx2mg转工程

### 联系方式
wx:oowen1985

**Comment by jesseband** [comment]
这个工具暂时还不成熟，先不要使用这种方法导出微信游戏
