### ISSUE TITLE
原生广告bug

### ISSUE THREAD

**Issue by xiaoweiLoveyou** [vivominigame/issues#24]
### 相关信息
- 问题类型

- 引擎版本

- 手机型号

**Comment by xiaoweiLoveyou** [comment]
原生广告api问题

**Comment by jesseband** [comment]
> 原生广告api问题

写出详细问题，怎么产生的，必现路径，手机环境

**Comment by xiaoweiLoveyou** [comment]
机型 ： vivo x20 
快游戏版本 ： 1053
游戏引擎 ： cocos creator 2.0.8
重现步骤 ： 创建原生广告，注销错误回调的时候必现 
重现代码 ：         
this.m_adObj = qg.createNativeAd({
        posId: posId,
});
var onError = function (res) {
       self.onAdError(res);
}
this.m_adObj.onError(onError);
this.m_adObj.offError(onError);  或者 this.m_adObj.offError();  

报错信息 ： this.m_adObj.offError is not a function

**Comment by jesseband** [comment]
> 机型 ： vivo x20
> 快游戏版本 ： 1053
> 游戏引擎 ： cocos creator 2.0.8
> 重现步骤 ： 创建原生广告，注销错误回调的时候必现
> 重现代码 ：
> this.m_adObj = qg.createNativeAd({
> posId: posId,
> });
> var onError = function (res) {
> self.onAdError(res);
> }
> this.m_adObj.onError(onError);
> this.m_adObj.offError(onError); 或者 this.m_adObj.offError();
> 
> 报错信息 ： this.m_adObj.offError is not a function

offError暂时没实现，下个版本完善掉

**Comment by xiaoweiLoveyou** [comment]
好的 了解了，那现在这个版本是不需要管原生广告的释放对吧

**Comment by jesseband** [comment]
> 好的 了解了，那现在这个版本是不需要管原生广告的释放对吧

嗯，可以
