### ISSUE TITLE
Unity小游戏在调试器1.10.1.803版本闪退

### ISSUE THREAD

**Issue by WpSmile** [vivominigame/issues#241]
小游戏调试器：
平台版本号：1101
平台版本名称：1.10.1.803

手机型号：
vivo S1
Android9.0

问题描述:
1.在上述版本调试器上正常情况下应能正常进入游戏
2.目前测试在该版本调试器上自定义Loading界面加载到54%闪退，测试其他调试器版本能正常进入游戏
3.自定义Loading方案中online_mini.data.unityweb及online_mini.wasm.code.unityweb使用zip压缩后的文件大小约为8M+，未压缩时大小约为30M+
[日志.txt](https://github.com/vivominigame/issues/files/9660845/default.txt)

联系方式
QQ:179292126

**Comment by yuebai008** [comment]
unity调试崩溃  该问题为平台问题   不开启调试可以正常进入 ，调试可以先用低版本 线上不会有影响  后续平台会进行修复
