### ISSUE TITLE
自定义loading 加载 wasm.zip 失败

### ISSUE THREAD

**Issue by guyun008** [vivominigame/issues#243]
![图片](https://user-images.githubusercontent.com/17018197/229729784-dabe5dcd-9429-4f02-aaef-3d102e0c8ff7.png)
全量 rpk 在小游戏调试器就没有问题，自定义 网络CDN加载就报这个错误。
Unity 2021
sdk 是最新版本。
本人QQ：1635761637

**Comment by xinyangcuncun** [comment]
此类问题通常是打包出来的wasm版本加载不对导致，建议排查下CDN缓存
