### ISSUE TITLE
unity小游戏手机运行报错 “Cannot read property 'writeText' of undefined,TypeError: Connot read property 'writeText' of undefined”

### ISSUE THREAD

**Issue by lischolar** [vivominigame/issues#244]
配置信息：
      unity版本：2019.4.35f1
      小游戏调试器：
      平台版本号：1083
      平台版本名称： 1.8.3.400
      手机型号：vivo x21A
      Android版本: 9

问题描述：
    1、当前按照文档进行正常打包，配置为以上信息，打包正常
    2、手机本地运行进入游戏后，在游戏首场景里报错：
        “Cannot read property 'writeText' of undefined,TypeError: Connot read property 'writeText' of undefined”
以下为报错信息：
![QQ图片20230410154301](https://user-images.githubusercontent.com/55233625/230853088-0a0f90fb-31ec-408d-b030-f70b52b666ee.png)
联系方式：
QQ:  137768802

**Comment by xinyangcuncun** [comment]
该问题是使用类似浏览器剪切板功能导致，小游戏没有这个能力
