### ISSUE TITLE
原生广告加载不出来

### ISSUE THREAD

**Issue by dogagithub** [vivominigame/issues#247]
### 相关信息
- 问题类型

广告加载
- 引擎版本

vivo1103
- 手机型号

V1986A
- 操作系统

- IDE版本

- toolkit版本

### 问题描述

![~B{%P0}Q%@3$U(VJL25S5FI](https://user-images.githubusercontent.com/1228178/233255704-76aaf68c-bd41-4322-9885-bbb8dab5a694.png)
从接入到过审发布，原生广告一直加载不到，重试了20次以上也加载不到
我们的Appid：105637821
### 复现步骤

进入游戏，加载原生广告时就报错
### 联系方式

已拉群

**Comment by xinyangcuncun** [comment]
排查广告问题可以看以下两个文档 ：
1、http://minigame.vivo.com.cn/documents/#/lesson/open-ability/ad
2、http://minigame.vivo.com.cn/documents/#/lesson/question/question-common
