### ISSUE TITLE
unity 打包 ，提示打包结束，但是对应文件夹下没有生成的包，请问一下官方，应该从哪些方面进行检查？

### ISSUE THREAD

**Issue by liqi777777** [vivominigame/issues#250]
unity 打包时，提示打包结束，但是对应文件夹下没有生成的包，请问一下官方，应该从哪些方面进行检查？

**Comment by liqi777777** [comment]
![image](https://github.com/vivominigame/issues/assets/64735006/1a052555-e45a-41ed-9e36-d574622921e1)
这个是我的打包文件夹

**Comment by xinyangcuncun** [comment]
> ![image](https://user-images.githubusercontent.com/64735006/246739752-1a052555-e45a-41ed-9e36-d574622921e1.png) 这个是我的打包文件夹

> ![image](https://user-images.githubusercontent.com/64735006/246739752-1a052555-e45a-41ed-9e36-d574622921e1.png) 这个是我的打包文件夹

正常打包的文件在webgl_vivo文件中，主要排查的方式是看打包过程中是否有报错。

如果打包报错，可以进一步通过Unity原生打包webgl是否正常，如果异常则需要先解决打包webgl异常问题

**Comment by 951704648** [comment]
![image](https://github.com/vivominigame/issues/assets/54766172/9feca8d0-7f58-4134-96eb-04fb6bcc0761)
![image](https://github.com/vivominigame/issues/assets/54766172/bc51c910-a3f6-445b-9dfd-7653120a138b)
打出来的包，这是正常的吗
