### ISSUE TITLE
Unity打包小游戏，手机上卡死

### ISSUE THREAD

**Issue by 951704648** [vivominigame/issues#253]
![image](https://github.com/vivominigame/issues/assets/54766172/10aac099-80eb-4599-ace4-adbdd8268fc2)建一个空项目，放一个Image.
![image](https://github.com/vivominigame/issues/assets/54766172/c506373f-5373-4105-8b05-3bfb05124530)
在这里卡10多秒
![image](https://github.com/vivominigame/issues/assets/54766172/1dfd479b-17f1-4014-90cd-96dc092d8f44)
然后过一会游戏就闪退了
主项目就OnEnable跑了，后续就不跑了 是我缺少啥配置吗，还是版本不对

**Comment by xinyangcuncun** [comment]
> ![image](https://user-images.githubusercontent.com/54766172/251176137-10aac099-80eb-4599-ace4-adbdd8268fc2.png)建一个空项目，放一个Image. ![image](https://user-images.githubusercontent.com/54766172/251176582-c506373f-5373-4105-8b05-3bfb05124530.png) 在这里卡10多秒 ![image](https://user-images.githubusercontent.com/54766172/251177243-1dfd479b-17f1-4014-90cd-96dc092d8f44.png) 然后过一会游戏就闪退了 主项目就OnEnable跑了，后续就不跑了 是我缺少啥配置吗，还是版本不对

使用的Unity版本是多少 目前仅支持 2019 到 2021  ，看调试器这个应用的内存已经达到1.8G，内存是异常的，是否在player setting 里面开启了调试 或者其他配置信息，正常空项目的内存在 300M 左右

**Comment by 951704648** [comment]
是版本太高了，降低版本就行了。还有一个问题，就是上线必须小于4M，多出来的之只能放服务器吗？

**Comment by 951704648** [comment]
> > ![image](https://user-images.githubusercontent.com/54766172/251176137-10aac099-80eb-4599-ace4-adbdd8268fc2.png)建一个空项目，放一个Image. ![image](https://user-images.githubusercontent.com/54766172/251176582-c506373f-5373-4105-8b05-3bfb05124530.png) 在这里卡10多秒 ![image](https://user-images.githubusercontent.com/54766172/251177243-1dfd479b-17f1-4014-90cd-96dc092d8f44.png) 然后过一会游戏就闪退了 主项目就OnEnable跑了，后续就不跑了 是我缺少啥配置吗，还是版本不对
> 
> 使用的Unity版本是多少 目前仅支持 2019 到 2021 ，看调试器这个应用的内存已经达到1.8G，内存是异常的，是否在player setting 里面开启了调试 或者其他配置信息，正常空项目的内存在 300M 左右

请问一下 最终上线超了4M，可以使用类似分包的办法提上去吗，就是包体都放本地，可行吗，因为我看到文档都是网络加载的

**Comment by yuebai008** [comment]
可以将unity资源或wasm放在分包内试下，目前是支持这样操作的，线上也已放宽了unity分包的大小限制，后期工具会优化，支持快速转换到分包本地加载
