### ISSUE TITLE
关于“上架审核模式”的疑问

### ISSUE THREAD

**Issue by yzytmac** [vivominigame/issues#254]
您好，请问小游戏调试器中的“开启上架审核模式”的作用是什么？有时候打开会发现一些莫名奇妙的bug，但又不太确定是此模式打开造成的。

**Comment by yuebai008** [comment]
上架审核模式主要是：
1、会在system打印一些性能日志：启动耗时、内存、帧率等
2、开启vconsole功能，可以在手机上直接查看日志数据
一般不会影响到游戏的运行，如果有问题，可以查看下vconsole看下是否有报错
