### ISSUE TITLE
VIVORPK 通过Unity转换，审核测试经常会出现卡死现象，采用同型号同平台测试机并不能复现卡死现象

### ISSUE THREAD

**Issue by Sidney19950816** [vivominigame/issues#257]
X21 1103 
经常审核会驳回游戏运行时走动碰撞会卡死
自测采用同型号，云测采用低端机型皆不能复现问题，审核驳回的Log里查询error  exception Unity 关键词都没有找到。
这个问题在审核时出现频率较高，请问如何才能避免或者准确定位问题？

**Comment by xinyangcuncun** [comment]
可以使用云测的手机 复现一下  https://minigame.vivo.com.cn/documents/#/lesson/dev/dev-onlinedevice

把相应的问题录屏附上看看

**Comment by Sidney19950816** [comment]
https://swsdl.vivo.com.cn/appstore/cloudtest/log/20230919/202309191047175985986829.zip  测试录屏

**Comment by Sidney19950816** [comment]
云测确实测不出来卡死,人都晕了
X20 X30 都没有

**Comment by Sidney19950816** [comment]
不知道为啥一到审核人员测试就卡死,是不是审核人员录屏占用内存啊

**Comment by 1072690884** [comment]
修改一下兼容的最低游戏引擎版本编号，测试的是最低游戏引擎版本测试，盲猜你们自己测试使用的是最新的游戏引擎版本

**Comment by Sidney19950816** [comment]
> 修改一下兼容的最低游戏引擎版本编号，测试的是最低游戏引擎版本测试，盲猜你们自己测试使用的是最新的游戏引擎版本

我们设置1103 测试1103一样的 手机 同型号 快应用同版本  X21  1103 
图片来自审核视频
![image](https://github.com/vivominigame/issues/assets/118795533/c8c4a7c8-288b-4780-ac35-66a135ac8527)

**Comment by Sidney19950816** [comment]
> 可以使用云测的手机 复现一下 https://minigame.vivo.com.cn/documents/#/lesson/dev/dev-onlinedevice
> 
> 把相应的问题录屏附上看看

为什么老驳回这个问题呀，只要是3D游戏，必卡死然后就给我驳回了，提供的log也没有啥报错，这让人怎么改啊？这几天不同的游戏都驳回几个了。哥哥们怎么回事啊？

**Comment by Sidney19950816** [comment]
审核的x21真的没问题嘛？

**Comment by xinyangcuncun** [comment]
> 审核的x21真的没问题嘛？

方便发我 一份日志链接么，或者录屏效果

**Comment by Sidney19950816** [comment]
> > 审核的x21真的没问题嘛？
> 
> 方便发我 一份日志链接么，或者录屏效果

您好，请您查看 https://swsdl.vivo.com.cn/appstore/cloudtest/log/20230919/202309191047175985986829.zip

**Comment by Sidney19950816** [comment]
> > > 审核的x21真的没问题嘛？
> > 
> > 
> > 方便发我 一份日志链接么，或者录屏效果
> 
> 您好，请您查看 https://swsdl.vivo.com.cn/appstore/cloudtest/log/20230919/202309191047175985986829.zip

需要提供rpk嘛？

**Comment by Sidney19950816** [comment]
或者我可以添加您的联系方式嘛？

**Comment by xinyangcuncun** [comment]
> 或者我可以添加您的联系方式嘛？

QQ ： 2241805577
