### ISSUE TITLE
W10 Unity2019.4.35f1c1版本js调用Promise会导致闪退

### ISSUE THREAD

**Issue by ws745630** [vivominigame/issues#259]
使用Unity导出vivo小游戏时，使用new Promise(function(reslove,reject){ })相关语法会导致游戏调试结束，想请问下这个是什么原因呢

**Comment by xinyangcuncun** [comment]
> 使用Unity导出vivo小游戏时，使用new Promise(function(reslove,reject){ })相关语法会导致游戏调试结束，想请问下这个是什么原因呢

应该是其他原因导致的，目前已知这个语法是没问题的

**Comment by ws745630** [comment]
应该是使用webgl 1.0导致的，我这边换成高版本就没问题了
