### ISSUE TITLE
关于首次创建banner不显示的问题

### ISSUE THREAD

**Issue by RuiZhuo** [vivominigame/issues#30]
hello。
我们这边在接banner的时候，调试时，首次创建的banner不会显示出来，也没有catch到错误。但是第二次创建的banner就可以正常显示。请问这个是什么原因造成的呢

**Comment by jesseband** [comment]
错误的回调，creat的是在onError里面，load，show等的回调在自己的catch里面，两个地方都捕捉下，

**Comment by RuiZhuo** [comment]
这两个地方也捕捉了，未捕获到任何错误信息

**Comment by RuiZhuo** [comment]
这两个地方也捕捉了，未捕获到任何错误信息

**Comment by RuiZhuo** [comment]
1
