### ISSUE TITLE
调用 qg.getUserInfo {"msg":"参数不合法","code":20000}

### ISSUE THREAD

**Issue by xss9981** [vivominigame/issues#35]
我接入方式为，小游戏简化模式，
参考文档为https://minigame.vivo.com.cn/documents/#/api/service/newaccount?id=key

通过登录token获取用户信息时，vivo接口返回{"msg":"参数不合法","code":20000}，
麻烦大大帮忙排查一下问题

**Comment by xss9981** [comment]
我这边是服务器调用。
http-get请求地址=https://quickgame.vivo.com.cn/api/quickgame/cp/account/userInfo

![20191105154923](https://user-images.githubusercontent.com/54100893/68188362-eec41e00-ffe3-11e9-8bb5-b731d14515b6.png)

**Comment by jesseband** [comment]
![image](https://user-images.githubusercontent.com/12119512/68189236-e5d44c00-ffe5-11e9-95f1-e9f67f8ed05b.png)
https://minigame.vivo.com.cn/documents/#/lesson/question/question-account

**Comment by jesseband** [comment]
多数情况是支付和账户的弄混了
![image](https://user-images.githubusercontent.com/12119512/68189319-07cdce80-ffe6-11e9-936a-3f8b2addbff8.png)

**Comment by reniu** [comment]
@xss9981 请问此问题解决了么，谢谢
