### ISSUE TITLE
Cocos老版本因分包需求升级到新版本黑屏

### ISSUE THREAD

**Issue by NavMeshSword** [vivominigame/issues#39]

**Comment by jesseband** [comment]
添加下详细描述，cocos版本，vivo引擎版本，怎么写的导致的黑屏
先看下我们文档 
https://minigame.vivo.com.cn/documents/#/lesson/base/subpackage
在看下cocos分包的文档 ，确认写法无误

**Comment by NavMeshSword** [comment]
Vivo调试器和引擎版本：
![IMG_20191107_163436](https://user-images.githubusercontent.com/49716337/68372848-a12ee900-017c-11ea-9f73-bed165e58f3d.jpg)
老版本和新版本开发工具都正常安装：
![image](https://user-images.githubusercontent.com/49716337/68372029-0b468e80-017b-11ea-9864-ccbd8e9ad4b1.png)
使用Cocos2.0.10进行开发时，游戏在vivo手机上正常运行
2.2rpk包(分包模式)和scirpt：
[2.2.zip](https://github.com/vivominigame/issues/files/3818600/2.2.zip)
2.0.10rpk包（整包模式）和script
[2.0.10.zip](https://github.com/vivominigame/issues/files/3818613/2.0.10.zip)
使用Cocos2.1.3和Cocos2.2进行开发时代码相同，构建rpk正常，但无论是分包还是不分包游戏在vivo手机上均黑屏。
这是Chrome调试信息：
![image](https://user-images.githubusercontent.com/49716337/68372275-7f813200-017b-11ea-968d-469005873b69.png)
