### ISSUE TITLE
原生广告拉取一直报错{"data":"param not null","code":200}

### ISSUE THREAD

**Issue by fenix32167** [vivominigame/issues#43]
- 问题类型
原生广告加载问题

- 引擎版本
vivo 1053

- 手机型号
vivo X7

### 问题描述
创建好原生广告后，load时一直报错{"data":"param not null","code":200}

### 复现步骤
```
this._nativeAd = qg.createNativeAd({
    posId: “7854ac56830e4cd1a74bc81872fd3d14”
});
this._nativeAd.onLoad(res => {
    this._nativeAdInfo = res.adList;
    this._nativeAd.offLoad();
    console.log("获得原生广告："+JSON.stringify(this._nativeAdInfo));
})
this._nativeAd.load().catch(f => {
    console.error("VIVO nativeAd error:" + JSON.stringify(f));
});
```
此时catch错误VIVO nativeAd error:{"data":"param not null","code":200}

### 联系方式

wx：fenix32167
csgame@qq.com

**Comment by weixing02** [comment]
> * 问题类型
>   原生广告加载问题
> * 引擎版本
>   vivo 1053
> * 手机型号
>   vivo X7
> 
> ### 问题描述
> 创建好原生广告后，load时一直报错{"data":"param not null","code":200}
> 
> ### 复现步骤
> ```
> this._nativeAd = qg.createNativeAd({
>     posId: “7854ac56830e4cd1a74bc81872fd3d14”
> });
> this._nativeAd.onLoad(res => {
>     this._nativeAdInfo = res.adList;
>     this._nativeAd.offLoad();
>     console.log("获得原生广告："+JSON.stringify(this._nativeAdInfo));
> })
> this._nativeAd.load().catch(f => {
>     console.error("VIVO nativeAd error:" + JSON.stringify(f));
> });
> ```
> 
> 此时catch错误VIVO nativeAd error:{"data":"param not null","code":200}
> 
> ### 联系方式
> wx：fenix32167
> [csgame@qq.com](mailto:csgame@qq.com)

原因是create与load之间调用间隔过短，我们这边会做修改兼容，目前暂时要调整一下create和load的调用时机

**Comment by fenix32167** [comment]
间隔过短不是很精确，我应该等多久才能load？

**Comment by weixing02** [comment]
> 间隔过短不是很精确，我应该等多久才能load？
一般来说100ms - 200ms就可以，之后会修复，更新在文档里

**Comment by chenyu0532** [comment]
我也遇到这个问题了，接了很多个游戏了，就单单那一个游戏出现这个错误，很费解

**Comment by jesseband** [comment]
> 我也遇到这个问题了，接了很多个游戏了，就单单那一个游戏出现这个错误，很费解

看下之前的回复，这个后续会修复
