### ISSUE TITLE
获取access_token接口报错"state":"4000"

### ISSUE THREAD

**Issue by Johnien** [vivominigame/issues#44]
https://passport.vivo.com.cn/oauth/2.0/access_token?timestamp=1573453684149&nonce=62d9eabb2t54r0aj&client_id=100001280&code=1b092575962bc0a36ada46dfc9f510c2&grant_type=authorization_code&sign=A374A8B6864BCD369ED953F17B56B9A9
{"error_description":"invalid request","state":"4000","error":"invalid_request"}

**Comment by jesseband** [comment]
建议使用新账户接口接入 http://minigame.vivo.com.cn/documents/#/api/service/newaccount
