### ISSUE TITLE
快游戏如何接入原生广告

### ISSUE THREAD

**Issue by Cooron** [vivominigame/issues#45]
如题，快游戏如何接入原生广告？看文档看不大明白。例如点击上报和展示上报，快应用内部如何得知原生广告被点击，从而执行上报动作？

**Comment by weixing02** [comment]
是哪一部分不明白呢？文档里提供了接入Demo，展示上报和点击上报只需要在广告加载成功后分别调用reportAdShow()和reportAdClick()就可以了，快应用内部会收到你的上报数据，需要注意的是每个广告的点击上报和展示上报分别只能生效一次

**Comment by Cooron** [comment]
> 是哪一部分不明白呢？文档里提供了接入Demo，展示上报和点击上报只需要在广告加载成功后分别调用reportAdShow()和reportAdClick()就可以了，快应用内部会收到你的上报数据，需要注意的是每个广告的点击上报和展示上报分别只能生效一次

后来懂了……文档里面应该写清楚需要自己展示拉下来的图片，根据图片点击和展示上报

**Comment by jesseband** [comment]
> > 是哪一部分不明白呢？文档里提供了接入Demo，展示上报和点击上报只需要在广告加载成功后分别调用reportAdShow()和reportAdClick()就可以了，快应用内部会收到你的上报数据，需要注意的是每个广告的点击上报和展示上报分别只能生效一次
> 
> 后来懂了……文档里面应该写清楚需要自己展示拉下来的图片，根据图片点击和展示上报

http://minigame.vivo.com.cn/documents/#/ui/ad 参考广告设计规范
