### ISSUE TITLE
原生广告具体怎么使用

### ISSUE THREAD

**Issue by jesseband** [vivominigame/issues#46]
请问一下，咱们渠道原生广告是什么形态的，如果是图片，图片尺寸是多大的，还是说我自己可以调整

**Comment by weixing02** [comment]
目前返回的原生广告有两种内容，一种是网址类，一种是应用下载类，形态都是图文混合，图片大小暂无限制，自己可以调整大小和位置，设计广告的展示形式，但之后会有相应的广告设计规范以及对返回的广告形态作区分（纯图、纯文、图文混合等），请关注文档更新

**Comment by weixing02** [comment]
https://minigame.vivo.com.cn/documents/#/ui/ad 开发者平台中提供了原生广告和其他广告的设计规范，请参考规范来设计和展示原生广告
