### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by xjywish** [vivominigame/issues#49]
打开调试器，显示黑屏
![image](https://user-images.githubusercontent.com/51790365/68731668-df5c5a80-060b-11ea-8d47-2a7ada4593e0.png)

**Comment by jesseband** [comment]
参考https://github.com/vivominigame/issues/issues/48

**Comment by xjywish** [comment]
> 参考#48
> 如果没有解决，请提交更多信息，以便排查问题
[pisa.txt](https://github.com/vivominigame/issues/files/3845417/pisa.txt)
打印出日志，小游戏未进入js层，已知打包环境 正常，无法知道具体 导致黑屏的原因

**Comment by xjywish** [comment]
![image](https://user-images.githubusercontent.com/51790365/68840828-6ab61880-06fe-11ea-8265-8319f5b031ba.png)
报错日志如上

**Comment by jesseband** [comment]
> ![image](https://user-images.githubusercontent.com/51790365/68840828-6ab61880-06fe-11ea-8265-8319f5b031ba.png)
> 报错日志如上

联系下cocos那边的人，让cocos的人帮忙看下问题，去cocos论坛搜索下相关内容
