### ISSUE TITLE
authorize账号授权登录问题

### ISSUE THREAD

**Issue by Smile1170601406** [vivominigame/issues#50]
qg.authorize({
            type: "token",
            scope: "scope.baseProfile",
)}
账号授权登录  进入authorize的fail 
Get AppId Failed! 200
已经登录vivo账号

**Comment by jesseband** [comment]
确认包名是否为在vivo开发者平台申请appid的包名进行打包

**Comment by jesseband** [comment]
账号目前上线了新账号，新账号目的是提升用户授权成功率，如果用户在其中一款小游戏授权新账号成功，接入新账号的小游戏将不会重新授权，可直接拿到用户信息，建议接入新账号https://minigame.vivo.com.cn/documents/#/api/service/newaccount
