### ISSUE TITLE
Vivo小游戏因声音调用频繁而卡顿

### ISSUE THREAD

**Issue by NavMeshSword** [vivominigame/issues#51]
游戏名称：贪吃蛇进化论
现象描述：在进行游戏（点击开始游戏后）的过程中，如果频繁地播放声音（例如频繁点击加速按钮），声音会有滞后，和其他平台相比没有那么流畅（OPPO,微信），并且游戏会卡顿，到最后，游戏会无法播放加速的声音，吃金币的声音，但还是有其他音乐（播放次数不太频繁），最后会卡死。在chrome真机调试中和adb logcat -s jswrapper中没有发现报错。
Cocos版本: 2.0.10
![image](https://user-images.githubusercontent.com/49716337/68750447-d59e1b80-063a-11ea-8e7d-1057265e56bd.png)
这是调用加速声音代码的截图，网不好暂时无法上传文件，望解决

**Comment by jesseband** [comment]
![image](https://user-images.githubusercontent.com/12119512/68753463-0c2a6500-0640-11ea-9778-d461655d9f10.png)
cocos使用2.1.3 引擎使用1053 先试试

**Comment by NavMeshSword** [comment]
现象：之前我们使用的1053和2.0.10会出现标题所述的问题，现在在你们的建议下，更换成了2.1.3和1054,虽然不会出现卡死的情况，但是仍然会在游戏中出现卡顿现象，如果禁用声音，则十分流畅。

问题，如果在发布后，用户的平台是1053那么会不会卡死？vivo公司自己测试的平台什么版本？
