### ISSUE TITLE
LayaAir IDE 1.8.5 发布vivo小游戏 Laya.loader.load()方法加载音乐文件 出现问题

### ISSUE THREAD

**Issue by heyuanshen** [vivominigame/issues#52]
项目：LayaAir IDE 1.8.5 新建项目（测试）
问题：在项目中使用Laya.loader.load()方法进行文件预加载，加载音乐文件(.mp3格式)，在Laya编辑器上按F5调试项目没有任何问题，在发包后，通过vivo调试器上进行测试，在加载音乐资源文件时就会卡住，弹出提示框，项目出错。
log日志：使用chrome真机调试查看log日志，没有错误以及警告。
以测试过的方法：
  1.禁止加载音乐文件（项目不出错，除了位图字体，其他资源都能加载完成）
  2.转换音乐文件格式（已测试格式：wav、ogg、mp3，都不能加载）
  3.通过console.log(Laya.loader.load("音乐文件资源目录"))，打印log能获取到对象，返回值不为undefined
其他：在没有加载音乐的情况下，通过Laya.SoundManager.playMusic("音乐资源目录")方法播放音乐，没有任何问题，能正常播放。
![U2~R13YY `@(7JK~)576SJL](https://user-images.githubusercontent.com/46129222/68761546-3c2d3480-064f-11ea-9eb3-bfcecc32c708.png)

**Comment by jesseband** [comment]
新的引擎版本会解决音频卡顿现象

**Comment by heyuanshen** [comment]
> 新的引擎版本会解决音频卡顿现象

我现在使用的：vivo调试器 平台版本号：1053 平台版本名称：1.5  LayaAir IDE1.8.5
这个问题是预加载，加载音频文件会卡住，log日志没有错误跟警告，所以加载页面会一直卡住，做过很多测试，都没有效果，主要是资源都是从网上获取，如果不能预加载没办法获取音频文件了
