### ISSUE TITLE
快应用接入原生广告的如何展示

### ISSUE THREAD

**Issue by hui963** [vivominigame/issues#54]
第一次接触原生广告
在demo 中看到有load 和onload  上报展示  但是不知道该如何展示在自己的游戏中

**Comment by jesseband** [comment]
参考https://github.com/vivominigame/issues/issues/46

**Comment by hui963** [comment]
> 参考#46
我不清楚的是     获取到的原生信息 是需要我自己创建一个展示区吗？

**Comment by hui963** [comment]
如果我自己创建展示区  用户的点击是由我来判断然后上报的吗?

**Comment by weixing02** [comment]
1. load和onLoad不是用于上报展示，而是分别用于加载和监听加载状态， 上报展示和上报点击事件分别调用的是reportAdShow和reportAdClick
2. 原生广告是需要自己设计和创建展示区域的，https://minigame.vivo.com.cn/documents/#/ui/ad开发者平台中提供了相关的设计规范，包括其他类型的广告设计规范
3. 点击事件由你自己监听，用户点击完成后你需要在点击事件中调用reportAdClick来上报点击事件

**Comment by weixing02** [comment]
load和onLoad不是用于上报展示，而是分别用于加载和监听加载状态， 上报展示和上报点击事件分别调用的是reportAdShow和reportAdClick
原生广告是需要自己设计和创建展示区域的，https://minigame.vivo.com.cn/documents/#/ui/ad 开发者平台中提供了相关的设计规范，包括其他类型的广告设计规范
点击事件由你自己监听，用户点击完成后你需要在点击事件中调用reportAdClick来上报点击事件
