### ISSUE TITLE
调用banner广告出现问题

### ISSUE THREAD

**Issue by oyzx** [vivominigame/issues#55]
在调用banner广告的时候，有时候banner能出现有时候不能，onError函数也没有报错，onShow函数也是正常的，出现的情况是onSize函数被调用了，没有出现的情况是onSize函数没有被调用

**Comment by weixing02** [comment]
这个问题会在下一个版本修复兼容，目前在内存不足的时候，广告实例对象被回收，有概率会出现你描述的问题
