### ISSUE TITLE
快应用调试器，首次安装rpk包，显示分包加载失败！

### ISSUE THREAD

**Issue by MrHuyaa** [vivominigame/issues#61]
### 相关信息
- 问题类型
分包加载失败

-IDE 
白鹭引擎  版本5.2.30

-引擎版本
vivo 1054

- 手机型号
vivo Z3

### 问题描述

我们游戏有使用分包加载，本地首次安装打开时，提示load subpackage failed，分包加载失败。但是第二次能够正常进游戏。之后打开游戏都是显示分包加载成功。

### 复现步骤
第一次：打开快应用调试器》本地安装》开始调试》查看日志  现象：卡加载，原因分包加载失败。
第二次：点退出》点开始调试》进游戏内》分包加载成功  现象：进入游戏

### 联系方式
980230037@qq.com

**Comment by jesseband** [comment]
判断下加载失败的话，重新加载下子包
下个版本会修复掉
