### ISSUE TITLE
2和原生广告能否一起加载

### ISSUE THREAD

**Issue by chessandcard** [vivominigame/issues#63]
一起加载一个能显示，另外一个就不能显示，如果我们要做自动刷新，比如banner，60秒刷新一次。是不是展示出来再上报才能刷新下一条。

**Comment by weixing02** [comment]
banner和插屏广告很容易过期，而且只有在上报曝光或者上报点击之后，调用load()才能拉取到新的广告，所以最好不要同时展示两个相同类型的广告
