### ISSUE TITLE
qg.login 使用一次后再次调用无效？

### ISSUE THREAD

**Issue by wangduoguo** [vivominigame/issues#67]
使用一次qg.login 后再次调用无效，没有任何回调
qg.login().then((res) => {
                    console.log(JSON.stringify(res), "VIVO LOGIN SUCCESS")
                }, (err) => {
                    console.log(JSON.stringify(err), "VIVO LOGIN ERROR");
                });

**Comment by wangduoguo** [comment]
版本：1053

**Comment by jesseband** [comment]
手机账户登录是否正常
