### ISSUE TITLE
申请广告位添加应用时，提示缺少参数

### ISSUE THREAD

**Issue by mobi2us** [vivominigame/issues#82]
- [ ] 缺失

### 详细描述
在https://adnet.vivo.com.cn/admin/app/list/1/add中新建快生态应用时，提示缺少参数。

### 你的提议和看法
文档中说明在此申请广告位，但对于错误提醒无相关说明指导CP如何进行下一步。

**Comment by jesseband** [comment]
参考 https://github.com/vivominigame/issues/issues/76
