### ISSUE TITLE
qg.login 登录返回 code 406

### ISSUE THREAD

**Issue by zenghaowei** [vivominigame/issues#84]
406对应什么问题

**Comment by jesseband** [comment]
网络问题或者用户取消登录

**Comment by zenghaowei** [comment]
我调试的时候手机需要和电脑保持同一IP，是不是因为代理导致的网络问题呢？

**Comment by jesseband** [comment]
> 我调试的时候手机需要和电脑保持同一IP，是不是因为代理导致的网络问题呢？

参考 https://github.com/vivominigame/issues/issues/9
