### ISSUE TITLE
npm run build 之后黑屏

### ISSUE THREAD

**Issue by zenghaowei** [vivominigame/issues#86]
我通过cocos creator成功构建APK包之后成功运行游戏。因为包体超过4M。我删除了build\qgame\engine\res目录里面的一些资源，重新npm run build，然后运行游戏一直黑屏。

**Comment by zenghaowei** [comment]
是不是因为调试器测试的时候加载不到远程资源呢？

**Comment by jesseband** [comment]
> 是不是因为调试器测试的时候加载不到远程资源呢？

资源加载不到是会黑屏的，不能直接删除资源
