### ISSUE TITLE
在4G网络下激励广告展示失败

### ISSUE THREAD

**Issue by esengine** [vivominigame/issues#87]
### 相关信息
- 问题类型
egret 5.2.30

- 引擎版本
vivo 1030

- 手机型号
vivo X20A

- IDE版本

- 操作系统

- toolkit版本

### 问题描述
4G网络下拉取视频返回错误码 errcode: -6  errMsg: load ad in wrong net,please check your net

**Comment by jesseband** [comment]
errmsg 显示是网络问题
