### ISSUE TITLE
Canvas2D支持的Api详细列表

### ISSUE THREAD

**Issue by idler8** [vivominigame/issues#90]
文档关于:

- [x] 缺失
- [ ] 错误
- [ ] 不确定？

### 详细描述
Canvas2D支持的Api详细列表没有

### 你的提议和看法
请支持Canvas2D开发

**Comment by jesseband** [comment]
- moveTo
lineTo

**Comment by idler8** [comment]
@jesseband 
drawImage好像会内部报错，是修正了么？

**Comment by jesseband** [comment]
> @jesseband
> drawImage好像会内部报错，是修正了么？

具体报什么错误，最新版本也会报吗？如果报，提供下简单的demo，我们这边跟进下

**Comment by idler8** [comment]
@jesseband 
HTMLImageElement is not defined[0]G.drawImage@(no finename);
平台版本名称：1.5
平台版本号1056

**Comment by jesseband** [comment]
> @jesseband
> HTMLImageElement is not defined[0]G.drawImage@(no finename);
> 平台版本名称：1.5
> 平台版本号1056

具体代码怎么写的，能提供个demo吗

**Comment by idler8** [comment]
@jesseband 
下个版本什么时候上？
版本号多少
谢谢

**Comment by jesseband** [comment]
> @jesseband
> 下个版本什么时候上？
> 版本号多少
> 谢谢

1057

**Comment by hhj1070827295** [comment]
> * fillRect

目前支持canvas.toDataURL的方法吗？我打印出的canvas原型中的toDataURL方法有点不会对劲,提示是：
Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at t.invokeGetter (<anonymous>:1:142)
如果无法支持的话，那截屏该用什么方法进行截屏？
![image](https://user-images.githubusercontent.com/41157233/100817991-31288a80-3484-11eb-9363-488b76e21c6e.png)
