### ISSUE TITLE
qg.login之后在后端使用api获取openid等信息是，总是返回retcode:20000的错误

### ISSUE THREAD

**Issue by reniu** [vivominigame/issues#93]
### 相关信息
- 问题类型

- 引擎版本

- 手机型号

**Comment by reniu** [comment]
不知道为啥，按照模板写的，结果好像什么信息都没有，这里补充下：

1，前端使用qg.login()登陆，能成功拿到token

2，后端使用此token，通过https://minigame.vivo.com.cn/documents/#/api/service/newaccount?
id=login这里文档的API：https://quickgame.vivo.com.cn/api/quickgame/cp/account/userInfo请求用户openid和其他信息，此时的返回总是{retcode: 20000}

3，我们已经反复检查，严格按照文档组织参数了

4，retcode = 20000具体是什么含义呢，可以在哪里查看错误码的说明？

5，其他的槽点：

1），在技术文档里，qg.login的成功回调参数结构被描述成这样：res.data.token；但实际上的参数结构是：res.token，没有中间的data

2），在技术文档里，后端api的返回结构是这样的：{code: 'xxxx', msg: ‘xxxx’, data: {}}；但实际上是{retcode: 'xxx'}

**Comment by jesseband** [comment]
是res.token

**Comment by a1027794510a** [comment]
兄弟，我跟你一样，你解决了吗？
