### ISSUE TITLE
加载分包时报错

### ISSUE THREAD

**Issue by wenlong1314** [vivominigame/issues#95]
### 相关信息
- 问题类型
不清楚

- 引擎版本
 vivo 1054

- 手机型号
vivo NEX 双屏版

- 操作系统

- IDE版本

- toolkit版本

### 问题描述
1 预期加载成功。
2 实际，第一次加载子包报错load subpackage failed
第二次加载子包成功

### 复现步骤
在调试器上。
用 adb shell pm clear com.vivo.hybrid 命令清理缓存后再启动游戏就会卡
加载子包时报错

### 联系方式
wxid_fic3c3oxz67v22

**Comment by jesseband** [comment]
参考https://github.com/vivominigame/issues/issues/61

**Comment by wenlong1314** [comment]
已经解决谢谢
